apps/login/urls.py
''' Login App URLS.py file. '''


from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register$', views.register, name='register'),
    url(r'^login$', views.login, name='login'),
    url(r'^logout$', views.logout, name='logout'),
]

apps/my_book/urls.py
from django.conf.urls import url
from.import views

app_name = 'mybook'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^addQuote$', views.addQuote, name='addQuote'),
    url(r'^addFavorite$', views.addFavorite, name='addFavorite')

]

myBook/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.login.urls', namespace='login')),
    url(r'^mybook/', include('apps.my_book.urls', namespace='mybook')),
]

apps/my_book/models.py
''' -*- coding: utf-8 -*- MYBOOK MODELS '''


from __future__ import unicode_literals
from django.db import models
from ..login.models import User


# Create your models here.
class QuoteManager(models.Manager):
    def addQuote(self, postData):
        results = {'status': True, 'errors': []}
        if len(postData['title']) < 3 and len(postData['content']) < 10:
            results['errors'].append('All fields must be filled out')
            results['status'] = False

        user = User.objects.get(id=postData['user_id'])
        if results['status']:

            try:
                quote = Quote.objects.create(
                    title=postData['title'],
                    content=postData['content'],
                    user_id=user,
                )
                quote.save()
            except:
                results['errors'].append('Error: Quote not created')
                return results

    def addFavorite(self, postData, user_id):
        results = {'status': True, 'errors': []}
        try:
            
            blog = Blog.objects.get(postData['quote_id'])
            user = User.objects.get(id=user_id)
            favorite = quote.favoriteQuotes.add(user)
            quote.save()
        except:
            results['errors'].append('Error: not favorited')

        return results



class Quote(models.Model):
    title = models.CharField(max_length=100)
    content = models.CharField(max_length=5000)
    user_id = models.ForeignKey('login.User', related_name='quote')
    # favorite = models.ManyToManyField('Quote', related_name='favorite_quotes')
    created_at = models.DateTimeField(auto_now_add=True)
    # edited_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = QuoteManager()

# class Edit(models.Model):
#     creation_date = models.DateTimeField(auto_now_add=True)
#     editor = models.ForeignKey(User)
#     quote = models.ForeignKey(Quote)

apps/my_book/views.py
''' -*- coding: utf-8 -*- MYBOOK VIEWS '''


from __future__ import unicode_literals
from django.shortcuts import render, redirect, HttpResponse
from django.contrib import messages
from .models import Quote, User


# Create your views here.
def index(request):

    if not checkAuth(request):
        return redirect('/')

    user = User.objects.get(id=request.session.get('id'))
    quote = Quote.objects.all().order_by('-created_at')[:5]
    context = {
        'user': user,
        'quotes': quote,
    }
    return render(request, 'my_book/index.html', context)


def addQuote(request):
    # print 'at addquote in views'
    if not checkAuth(request):
        return redirect('/')

    if request.POST:
        results = Quote.objects.addQuote(request.POST)
        if results:
            messages.info(request, 'Quote Added')
        else:
            for error in results:
                messages.error(request, error)
            return redirect('mybook:addQuote')
        return redirect('mybook:index')

    user = User.objects.get(id=request.session.get('id'))
    context = {
        'user': user,
    }
    return render(request, 'my_book/addQuote.html', context)


def addFavorite(request):
    print 'at favorites in views'
    if request.POST:
        results = Quote.objects.addFavorite(request.POST, request.session['id'])
        if results:
            messages.info(request, 'Favorited!')
        else:
            for error in results:
                messages.error(request, error)
        return redirect('mybook:index')


def checkAuth(request):  # Force non-authorized user back to login/registration page
    try:
        if not request.session.get('id'):
            messages.error(request, 'Sorry, you\'re not logged in!')
            return False
        return True
    except:
        messages.error(request, 'Sorry, you\'re not logged in')
        return False

apps/my_book/templates/my_book/addQuote.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Add Quote</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body>
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
        <form action="{% url 'mybook:addQuote' %}" method="POST">
            {% csrf_token %}
            <input type="text" name="title" placeholder="Enter Quote Author" autofocus><br>
            <textarea name="content" rows="5" cols="50"></textarea><br>
            <input type="hidden" name="user_id" value="{{user.id}}">
            <button type="submit" name="submit" value="submit">Add!</button>
        </form>
    </body>
</html>

apps/my_book/templates/my_book/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>My Quotes</title>
        <meta charset="UTF-8">
    </head>
    <body>
        {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                    <li>{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        <a href="{% url 'mybook:index' %}">Home</a>
        <a href="{% url 'mybook:addQuote' %}">Add Quote</a>
        <a href="{% url 'login:logout' %}">Logout</a>
    <h1>{{user.username}}'s Quotes</h1>
    {# {% with user_id.favorites.all as favorite_quotes %}
    {% for quote in quote_list %}
    {% if quote in favorite_quotes %}Favorited{% endif %}
    ...
    {% endfor %}
    {% endwith %}#}
    {% for quote in quotes %}
    <div>
        <h1>{{quote.title}}</h1>
            Created: {{quote.created_at}}
        <div>
            {{quote.content}}<br>
            {# {{quote.Favorite.all.count}} Favorited this!#}
            {% if quote.user_id != user %}
                <form action="{% url 'mybook:addFavorite' %}" method="POST">
                    {% csrf_token %}
                    <button type="submit" name="submit" value="submit">Favorite!</button>
                    <input type="hidden" name="quote_id" value="{{quote.id}}">
                </form>
            {% endif %}
        </div>
    {% endfor %}
    <h3></h3>
    </body>
</html>